model_path: "RealVis"

num_inference_steps: 20

guidance_scale: 10

strength: 1

clip_slip: 1

padding_mask_crop: 7

prompt: "remove text, preserve background, highres, quality"

negative_prompt: "deformed, weird, bad resolution, bad depiction, blurry, not relevant"
